import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider>
      <body className={inter.className}>
        
      <header>
        <nav class="bg-yellow-400 border-gray-200 px-4 lg:px-6 py-2.5  ">
            <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl">
                <a href="/" class="flex items-center justify-center ">
                   
                    <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white ">CryptoCurrency Exchange App</span>
                </a>
                
               
            </div>
        </nav>
    </header>{children}</body>
      </StoreProvider>
    </html>
  );
}
